### ISSUE TITLE
Bug: Cannot Deploy

### ISSUE THREAD

**Issue by zcor** [Promise-Protocol/volumegauge#10]
When I fill in appropriate endpoints / private keys I am able to use the deploy.py file I added to the repository to deploy volumegaugetracker.vy successfully, but it returns this error on swap_volumegauge.vy

`Traceback (most recent call last):
  File "deploy.py", line 31, in <module>
    construct_txn = contract_.constructor().buildTransaction({
  File "/Users/gerrithall/life/crypto/git/volumegauge/gauge/lib/python3.7/site-packages/web3/contract.py", line 394, in constructor
    **kwargs)
  File "/Users/gerrithall/life/crypto/git/volumegauge/gauge/lib/python3.7/site-packages/web3/contract.py", line 603, in __init__
    self.data_in_transaction = self._encode_data_in_transaction(*args, **kwargs)
  File "/Users/gerrithall/life/crypto/git/volumegauge/gauge/lib/python3.7/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/gerrithall/life/crypto/git/volumegauge/gauge/lib/python3.7/site-packages/web3/contract.py", line 615, in _encode_data_in_transaction
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "/Users/gerrithall/life/crypto/git/volumegauge/gauge/lib/python3.7/site-packages/web3/_utils/abi.py", line 434, in merge_args_and_kwargs
    len(args) + len(kwargs),
TypeError: Incorrect argument count.  Expected '5'.  Got '0'`

**Comment by taariq** [comment]
resolved with new deploys scripts
